(()=>{
  let deferredPrompt=null,offlineReady=false;
  const buttons=()=>[document.querySelector('#installBacheckButtonFa'),document.querySelector('#installBacheckButtonEn')].filter(Boolean);
  const statusFa=()=>document.querySelector('#installStatusFa'),statusEn=()=>document.querySelector('#installStatusEn');
  const standalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true;
  const isIOS=()=>/iphone|ipad|ipod/i.test(navigator.userAgent||'');
  function setStatus(fa,en){if(statusFa())statusFa().textContent=fa;if(statusEn())statusEn().textContent=en}
  function sync(){if(standalone()){buttons().forEach(b=>b.disabled=true);setStatus('BACHECK روی این دستگاه نصب شده است.','BACHECK is installed on this device.');return}buttons().forEach(b=>b.disabled=false);if(deferredPrompt)setStatus('نصب مستقیم آماده است. روی «نصب BACHECK» بزنید.','Direct installation is ready. Select “Install BACHECK”.');else if(isIOS())setStatus('در iPhone / iPad نصب از طریق Safari → Share → Add to Home Screen انجام می‌شود.','On iPhone / iPad, install from Safari → Share → Add to Home Screen.');else if(offlineReady)setStatus('فایل‌های آفلاین آماده‌اند. اگر نصب مستقیم نمایش داده نمی‌شود، از منوی مرورگر Install app یا Add to Home screen را انتخاب کنید.','Offline files are ready. If direct install is unavailable, use the browser menu and choose Install app or Add to Home screen.')}
  window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;sync()});
  async function install(){if(standalone()){sync();return}if(!deferredPrompt){if(isIOS())setStatus('در Safari روی Share بزنید و Add to Home Screen را انتخاب کنید.','In Safari, tap Share and choose Add to Home Screen.');else setStatus('اگر پنجره نصب مستقیم ظاهر نشد، از منوی Chrome / Edge گزینه Install app یا Add to Home screen را انتخاب کنید.','If the direct prompt is unavailable, use the Chrome / Edge menu and choose Install app or Add to Home screen.');return}const prompt=deferredPrompt;deferredPrompt=null;try{await prompt.prompt();const choice=await prompt.userChoice;if(choice?.outcome==='accepted')setStatus('در حال نصب BACHECK… پس از نصب، برنامه را یک‌بار با اینترنت باز نگه دارید.','Installing BACHECK… After installation, keep it open once while online.');else setStatus('نصب انجام نشد. هر زمان خواستید دوباره «نصب BACHECK» را انتخاب کنید.','Installation was not completed. You can select “Install BACHECK” again later.')}catch(_){setStatus('نصب مستقیم در این مرورگر در دسترس نیست؛ از منوی مرورگر Install app را انتخاب کنید.','Direct installation is not available in this browser; use the browser menu and choose Install app.')}}
  buttons().forEach(button=>button.addEventListener('click',install));window.addEventListener('appinstalled',()=>{deferredPrompt=null;sync()});
  if('serviceWorker' in navigator)window.addEventListener('load',async()=>{try{await navigator.serviceWorker.register('./service-worker.js',{scope:'./'});await navigator.serviceWorker.ready;offlineReady=true;document.documentElement.classList.add('bacheck-offline-ready');sync()}catch(error){console.error('BACHECK service worker registration failed',error);setStatus('ذخیره آفلاین کامل نشد. اتصال اینترنت و HTTPS سایت را بررسی کنید.','Offline setup did not complete. Check the internet connection and that the site is served over HTTPS.')}});else setStatus('این مرورگر از نصب آفلاین BACHECK پشتیبانی نمی‌کند.','This browser does not support BACHECK offline installation.');
})();